version: 0.2
phases:
  build:
    commands:
      - echo Packing JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - spring-boot-cicd/target/spring-boot-cicd.jar
  discard-paths: yes